#!/usr/bin/env sh

set -e

install_configs() {
    mkdir -p ~/.config/i3
    cp ./configs/i3.config ~/.config/i3/config
    cp ./configs/zsh.config ~/.zshrc
}

if [ $# -eq 0 ]; then
  echo "usage: $0 CONFIG"
  echo "Possible configs:"
  echo "  ctfbox   Install the CTF NixOS configuration"
  echo "  help     Show this help text"
  echo "Note:"
  echo "  Make sure you have the necessary permissions to run these commands."
  echo "  It is recommended to run this script with superuser privileges."
  exit 1
fi

case "$1" in
  "ctfbox")
    echo "[+] Rebuilding NixOS CTF configuration for you..."
    install_configs
    sudo cp ./machines/ctfbox.nix /etc/nixos/configuration.nix
    sudo nixos-rebuild switch
    echo "[!] DONE!"
    ;;
  "help")
    echo "+---- NIXOS utility ---+"
    echo "usage: $0 CONFIG"
    ;;
  *)
      echo "Invalid argument. Exiting..."
      exit 1
      ;;
esac
