#!/usr/bin/env sh

set -xe

if [ $# -eq 0 ]; then
  echo "usage: install <command>"
  exit 1
fi

case "$1" in
  "ctf")
    echo "[+] Rebuilding NixOS CTF configuration for you..."
    sudo cp ./machines/ctfbox.nix /etc/nixos/configuration.nix
    sudo nixos-rebuild switch
    echo "[!] DONE!"
  "help")
    echo "+---- NIXOS utility ---+"
    echo "usage: install <command>"
  *)
    echo "Invalid argument. Exiting..."
    exit 1
    ;;
esac